"""empty message

Revision ID: 0505e92e2186
Revises: 833df5c90a9c
Create Date: 2024-01-12 04:04:24.718506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0505e92e2186'
down_revision = '833df5c90a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=120), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pay')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
