"""empty message

Revision ID: 7dbb958524b1
Revises: ede59818bb48
Create Date: 2024-01-12 18:17:17.381280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbb958524b1'
down_revision = 'ede59818bb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_paypal', sa.String(length=120), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('secret_paypal')

    # ### end Alembic commands ###
